<div class="header"><?php echo $this->_lang['messages_title']; ?></div>
<div id="messages-tabs">
    <ul>
        <?php if(isset($_REQUEST['id']) && $_REQUEST['m']=='r') { ?>
        <li><a href="#messages-read"><?php echo $this->_lang['messages_read_message']; ?></a></li>
        <?php } ?>
        <li><a href="#messages-inbox"><?php echo $this->_lang['messages_inbox']; ?></a></li>
        <li><a href="#messages-sent"><?php echo $this->_lang['messages_sent_tab']; ?></a></li>
        <li><a href="#messages-compose"><?php echo $this->_lang['messages_compose']; ?></a></li>
    </ul>
    <?php if(isset($_REQUEST['id']) && $_REQUEST['m']=='r') { ?>
    <div id="messages-read">
    <?php
      $sql = "SELECT * FROM ".$this->db."user_messages WHERE ".$this->db."user_messages.id=".$_REQUEST['id'];
      $rs = $this->dbQuery($sql);
      $limit = $this->recordCount($rs);
      if($limit!=1) {
        echo "Wrong number of messages returned!";
      } else {
        $message=$this->fetchRow($rs);
        if($message['recipient'] != $_SESSION['internalKey'] && $message['sender'] != $_SESSION['internalKey']) {
          echo $this->_lang['messages_not_allowed_to_read'];
        } else {
          // output message!
          // get the name of the sender
          $sender = $message['sender'];
          if($sender==0) {
            $sendername = $this->_lang['messages_system_user'];
          } else {
            $sql = "SELECT username FROM ".$this->db."manager_users WHERE id=$sender";
            $rs2 = $this->dbQuery($sql);
            $row2 = $this->fetchRow($rs2);
            $sendername = $row2['username'];
          }
      ?>
    
      <table style="width:100%;" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td colspan="2">
            <div>
              <span class="floatLeft">
                <?php if ($message['sender'] != $_SESSION['internalKey']) { ?>
                <input type="button" onClick="Etomite.myMessages('m=rp&id=<?php echo $message['id']; ?>');" value="<?php echo $this->_lang['messages_reply']; ?>" />
                <?php } ?>
                <input type="button" onClick="Etomite.myMessages('m=f&id=<?php echo $message['id']; ?>');" value="<?php echo $this->_lang['messages_forward']; ?>" />
                <input type="button" onClick="Etomite.deleteMyMessage('<?php echo $message['id']; ?>');" value="<?php echo $this->_lang["delete"]; ?>" />
              </span>
            </div>
        </td>
        </tr>
        <tr>
          <td colspan="2">&nbsp;</td>
        </tr>
        <tr>
          <td style="width: 100px;"><b><?php echo $this->_lang['messages_from']; ?>:</b></td>
          <td style="width: auto;"><?php echo $sendername; ?></td>
        </tr>
        <tr>
          <td><b><?php echo $this->_lang['messages_sent']; ?>:</b></td>
          <td><?php echo strftime($this->config['date_format'].' @ '.$this->config['time_format'], $message['postdate']+$this->config['server_offset_time']); ?></td>
        </tr>
        <tr>
          <td><b><?php echo $this->_lang['messages_subject']; ?>:</b></td>
          <td><?php echo $message['subject']; ?></td>
        </tr>
        <tr>
          <td colspan="2">&nbsp;</td>
        </tr>
        <tr>
          <td colspan="2">
        <?php
        // format the message :)
        $message = str_replace ("\n", "<br />", $message['message']);
        $dashcount = substr_count($message, "-----");
        $message = str_replace ("-----", "<i style='color:#666;'>", $message);
        for( $i=0; $i<$dashcount; $i++ ){
        $message .= "</i>";
        }
    
        echo "<div style=\"width:inherit; border:1px solid #000; padding:5px; background:#fff;\">$message</div>";
        ?>
    
        </td>
        </tr>
      </table>
    
      <?php
          // mark the message as read
          $sql = "UPDATE ".$this->db."user_messages SET ".$this->db."user_messages.messageread=1 WHERE ".$this->db."user_messages.id=".$_REQUEST['id'];
          $rs = $this->dbQuery($sql);
        }
      }
      ?>
    </div>
    <?php } ?>
    <div id="messages-inbox">
      <?php
      // Get  number of rows
      $sql = "SELECT count(id) FROM ".$this->db."user_messages WHERE recipient=".$_SESSION['internalKey']."";
      $rs=$this->dbQuery($sql);
      $countrows = $this->fetchRow($rs);
      $num_rows = $countrows['count(id)'];
    
      // ==============================================================
      // Example Usage
      // Note: I make 2 query to the database for this exemple, it
      // could (and should) be made with only one query...
      // ==============================================================
    
      // If current position is not set, set it to zero
      if( !isset( $_REQUEST['int_cur_position'] ) || $_REQUEST['int_cur_position'] == 0 ){
        $int_cur_position = 0;
      } else {
        $int_cur_position = $_REQUEST['int_cur_position'];
      }
    
      // Number of result to display on the page, will be in the LIMIT of the sql query also
      $int_num_result = $this->config['number_of_messages'];
    
      $extargv = ""; // extra argv here (could be anything depending on your page)
    
      include_once("includes/paginate.inc.php");
      // New instance of the Paging class, you can modify the color and the width of the html table
      $p = new Paging( $num_rows, $int_cur_position, $int_num_result, $extargv );
    
      // Load up the 2 array in order to display result
      $array_paging = $p->getPagingArray();
      $array_row_paging = $p->getPagingRowArray();
    
      // Display the result as you like...
      $pager .= $this->_lang['showing']." ". $array_paging['lower'];
      $pager .=  " ".$this->_lang['to']." ". $array_paging['upper'];
      $pager .=  " (". $array_paging['total']." ".$this->_lang['total'].")";
      $pager .=  "<br />". $array_paging['previous_link'] ."<<</a> " ;
      for( $i=0; $i<sizeof($array_row_paging); $i++ ){
        $pager .=  $array_row_paging[$i] ."&nbsp;";
      }
      $pager .=  $array_paging['next_link'] .">></a>";
    
      // The above example prints something like:
      // Results 1 to 20 of 597  <<< 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 >>>
      // Of course you can now play with array_row_paging in order to print only the results you would like...
    
      $sql = "SELECT * FROM ".$this->db."user_messages WHERE ".$this->db."user_messages.recipient=".$_SESSION['internalKey']." ORDER BY postdate DESC LIMIT ".$int_cur_position.", ".$int_num_result;
      $rs = $this->dbQuery($sql);
      $limit = $this->recordCount($rs);
      if($limit<1) {
        echo $this->_lang['messages_no_messages'];
      } else {
      echo $pager;
      ?>
    
        <table border=0 cellpadding=0 cellspacing=0  class="sort-table" id="table-1" style="width:100%;">
          <thead>
            <tr>
              <td width="12"></td>
              <td width="50%"><b><?php echo $this->_lang['messages_subject']; ?></b></td>
              <td><b><?php echo $this->_lang['messages_from']; ?></b></td>
              <td><b><?php echo $this->_lang['messages_private']; ?></b></td>
          <td width="150px"><b><?php echo $this->_lang['messages_sent']; ?></b></td>
            </tr>
          </thead>
          <tbody>
    
        <?php
          for ($i = 0; $i < $limit; $i++) {
            $message = $this->fetchRow($rs);
            $sender = $message['sender'];
            if($sender==0) {
              $sendername = "[System]";
            } else {
              $sql = "SELECT username FROM ".$this->db."manager_users WHERE id=$sender";
              $rs2 = $this->dbQuery($sql);
              $row2 = $this->fetchRow($rs2);
              $sendername = $row2['username'];
            }
            $classname = ($i % 2) ? 'class="even" ' : 'class="odd" ';
            $messagestyle = $message['messageread']==0 ? "messageUnread" : "messageRead";
        ?>
          <tr <?php echo $classname; ?>>
          <td ><?php echo $message['messageread']==0 ? "<img src='".MANAGER_URL."images/icons/new1-09.gif'>" : ""; ?></td>
            <td class="<?php echo $messagestyle; ?>" style="cursor: pointer; text-decoration: underline;" onClick="Etomite.myMessages('id=<?php echo $message['id']; ?>&m=r');">
              <?php echo $message['subject']; ?>
            </td>
          <td ><?php echo $sendername; ?></td>
          <td ><?php echo $message['private']==0 ? "No" : "Yes"; ?></td>
            <td ><?php echo strftime($this->config['date_format'].' @ '.$this->config['time_format'], $message['postdate']+$this->config['server_offset_time']); ?></td>
          </tr>
    
          <?php
            }
        }
        ?>
      </tbody>
      </table>
    </div>
    <div id="messages-sent">
      <?php
      // Get  number of rows
      $sql = "SELECT count(id) FROM ".$this->db."user_messages WHERE type LIKE 'Message Sent%' AND sender=".$_SESSION['internalKey']."";
      $rs=$this->dbQuery($sql);
      $countrows = $this->fetchRow($rs);
      $num_rows = $countrows['count(id)'];
    
      // ==============================================================
      // Example Usage
      // Note: I make 2 query to the database for this exemple, it
      // could (and should) be made with only one query...
      // ==============================================================
    
      // If current position is not set, set it to zero
      if( !isset( $_REQUEST['int_cur_position'] ) || $_REQUEST['int_cur_position'] == 0 ){
        $int_cur_position = 0;
      } else {
        $int_cur_position = $_REQUEST['int_cur_position'];
      }
    
      // Number of result to display on the page, will be in the LIMIT of the sql query also
      $int_num_result = $this->config['number_of_messages'];
    
      $extargv = ""; // extra argv here (could be anything depending on your page)
    
      include_once("includes/paginate.inc.php");
      // New instance of the Paging class, you can modify the color and the width of the html table
      $p = new Paging( $num_rows, $int_cur_position, $int_num_result, $extargv );
      $pager = '';
      // Load up the 2 array in order to display result
      $array_paging = $p->getPagingArray();
      $array_row_paging = $p->getPagingRowArray();
    
      // Display the result as you like...
      $pager .= $this->_lang['showing']." ". $array_paging['lower'];
      $pager .=  " ".$this->_lang['to']." ". $array_paging['upper'];
      $pager .=  " (". $array_paging['total']." ".$this->_lang['total'].")";
      $pager .=  "<br />". $array_paging['previous_link'] ."<<</a> " ;
      for( $i=0; $i<sizeof($array_row_paging); $i++ ){
        $pager .=  $array_row_paging[$i] ."&nbsp;";
      }
      $pager .=  $array_paging['next_link'] .">></a>";
    
      // The above example prints something like:
      // Results 1 to 20 of 597  <<< 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 >>>
      // Of course you can now play with array_row_paging in order to print only the results you would like...
    
      $sql = "SELECT * FROM ".$this->db."user_messages WHERE type LIKE 'Message Sent%' AND ".$this->db."user_messages.sender=".$_SESSION['internalKey']." ORDER BY postdate DESC LIMIT ".$int_cur_position.", ".$int_num_result;
      $rs = $this->dbQuery($sql);
      $limit = $this->recordCount($rs);
      if($limit<1) {
        echo $this->_lang['messages_no_sent'];
      } else {
      echo $pager;
      ?>
    
        <table border=0 cellpadding=0 cellspacing=0  class="sort-table" id="table-1" style="width:100%;">
          <thead>
            <tr>
              <td width="12"></td>
              <td width="50%"><b><?php echo $this->_lang['messages_subject']; ?></b></td>
              <td><b><?php echo $this->_lang['messages_to']; ?></b></td>
              <td><b><?php echo $this->_lang['messages_private']; ?></b></td>
          <td width="150px"><b><?php echo $this->_lang['messages_sent']; ?></b></td>
            </tr>
          </thead>
          <tbody>
    
        <?php
          for ($i = 0; $i < $limit; $i++) {
            $message = $this->fetchRow($rs);
            $recipient = $message['recipient'];
            if($recipient == 0) {
              $type = $message['type'];
              $type = explode(";", $type);
              $type = explode("|", $type[1]);
              $who = trim($type[0]);
              $typeId = isset($type[1]) ? trim($type[1]):'';
              if ($who == 'everyone') {
                  $receivername = "[Everyone]";
              } elseif ($who == 'group') {
                  $sql = "SELECT name FROM ".$this->db."user_roles WHERE id=$typeId";
                  $rs2 = $this->dbQuery($sql);
                  $row2 = $this->fetchRow($rs2);
                  $receivername = $row2['name'];
              }
            } else {
              $sql = "SELECT username FROM ".$this->db."manager_users WHERE id=$recipient";
              $rs2 = $this->dbQuery($sql);
              $row2 = $this->fetchRow($rs2);
              $receivername = $row2['username'];
            }
            $classname = ($i % 2) ? 'class="even" ' : 'class="odd" ';
            $messagestyle = $message['messageread']==0 ? "messageUnread" : "messageRead";
        ?>
          <tr <?php echo $classname; ?>>
          <td ><?php echo $message['messageread']==0 ? "<img src='".MANAGER_URL."images/icons/new1-09.gif'>" : ""; ?></td>
            <td class="<?php echo $messagestyle; ?>" style="cursor: pointer; text-decoration: underline;" onClick="Etomite.myMessages('id=<?php echo $message['id']; ?>&m=r');">
              <?php echo $message['subject']; ?>
            </td>
          <td ><?php echo $receivername; ?></td>
          <td ><?php echo $message['private']==0 ? "No" : "Yes"; ?></td>
            <td ><?php echo strftime($this->config['date_format'].' @ '.$this->config['time_format'], $message['postdate']+$this->config['server_offset_time']); ?></td>
          </tr>
    
          <?php
            }
        }
        ?>
      </tbody>
      </table>
    </div>
    <div id="messages-compose">
      <?php
      $composeFlag = false;
      if(($_REQUEST['m']=='rp' || $_REQUEST['m']=='f') && isset($_REQUEST['id'])) {
        $sql = "SELECT * FROM ".$this->db."user_messages WHERE ".$this->db."user_messages.id=".$_REQUEST['id'];
        $rs = $this->dbQuery($sql);
        $limit = $this->recordCount($rs);
        if($limit!=1) {
          echo "Wrong number of messages returned!";
        } else {
          $message=$this->fetchRow($rs);
          //if($message['recipient']!=$_SESSION['internalKey']) {
          if($message['recipient'] != $_SESSION['internalKey'] && $message['sender'] != $_SESSION['internalKey']) {
            echo $this->_lang['messages_not_allowed_to_read'];
          } else {
            // output message!
            // get the name of the sender
            $sender = $message['sender'];
            if($sender==0) {
              $sendername = "[System]";
            } else {
              $sql = "SELECT username FROM ".$this->db."manager_users WHERE id=$sender";
              $rs2 = $this->dbQuery($sql);
              $row2 = $this->fetchRow($rs2);
              $sendername = $row2['username'];
            }
            $subjecttext = $_REQUEST['m']=='rp' ? "Re: " : "Fwd: ";
            $subjecttext .= $message['subject'];
            $messagetext = "\n\n\n-----\n".$this->_lang['messages_from'].": $sendername\n".$this->_lang['messages_sent'].": ".strftime($this->config['date_format'].' @ '.$this->config['time_format'], $message['postdate']+$this->config['server_offset_time'])."\n".$this->_lang['messages_subject'].": ".$message['subject']."\n\n".$message['message'];
            if($_REQUEST['m']=='rp') {
              $recipientindex = $message['sender'];
            }
            $composeFlag = true;
          }
        }
      }
      ?>
    
      <script type="text/javascript">
      function hideSpans(showSpan) {
        $('#userspan').hide();
        $('#groupspan').hide();
        $('#allspan').hide();
        if(showSpan==1) {
          $('#userspan').show();
        }
        if(showSpan==2) {
          $('#groupspan').show();
        }
        if(showSpan==3) {
          $('#allspan').show();
        }
      }
      </script>
    
      <form method="post" name="messagefrm" id="messagefrm" onsubmit="return false;">
        <fieldset style="width:auto;">
        <legend><b><?php echo $this->_lang['messages_send_to']; ?>:</b></legend>
        <table width="100%"  border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>
          <input type=radio name="sendto" value="u" checked onClick='hideSpans(1);'><?php echo $this->_lang['messages_user']; ?>&nbsp;&nbsp;&nbsp;
          <input type=radio name="sendto" value="g" onClick='hideSpans(2);'><?php echo $this->_lang['messages_group']; ?>&nbsp;&nbsp;&nbsp;
          <input type=radio name="sendto" value="a" onClick='hideSpans(3);'><?php echo $this->_lang['messages_all']; ?>&nbsp;&nbsp;<br />
          <span id='userspan' style="display:block;"> <?php echo $this->_lang['messages_select_user']; ?>:&nbsp;
          <?php
          // get all usernames
          $sql = "SELECT username, id FROM ".$this->db."manager_users";
          $rs = $this->dbQuery($sql);
          ?>
          <select name="user" class="inputBox" style="width:150px">
            <option value="">Select a User</option>
          <?php
            while ($row = $this->fetchRow($rs)) {
          ?>
              <option value="<?php echo $row['id']; ?>" <?php echo (isset($sender) && $sender == $row['id']) ? "selected='selected'" : '' ?> ><?php echo $row['username']; ?></option>
        <?php } ?>
          </select>
          </span>
          <span id='groupspan' style="display:none;"> <?php echo $this->_lang['messages_select_group']; ?>:&nbsp;
          <?php
          // get all usernames
          $sql = "SELECT name, id FROM ".$this->db."user_roles";
          $rs = $this->dbQuery($sql);
          ?>
          <select name="group" class="inputBox" style="width:150px">
            <option value="">Select a group</option>
          <?php
          while ($row = $this->fetchRow($rs)) {
            ?>
            <option value="<?php echo $row['id']; ?>" ><?php echo $row['name']; ?></option>
          <?php } ?>
          </select>
          </span>
          <span id='allspan' style="display:none;"></span>
            </td>
            </tr>
          </table>
          </fieldset>
    
        <fieldset style="width:auto;">
        <legend><b><?php echo $this->_lang['messages_message']; ?>:</b></legend>
    
        <table width="100%"  border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td><?php echo $this->_lang['messages_subject']; ?>:</td>
            <td><input name="messagesubject" type=text class="inputBox" style="width: 500px;" maxlength="60" value="<?php echo $subjecttext; ?>"></td>
          </tr>
          <tr>
            <td valign="top"><?php echo $this->_lang['messages_message']; ?>:</td>
            <td><textarea name="messagebody" style="width:98%; height: 200px;" class="inputBox"><?php echo $messagetext; ?></textarea></td>
          </tr>
          <tr>
            <td></td>
          </tr>
        </table>
    
          <div>
            <span class="floatLeft">
              <img src="<?php echo MANAGER_URL; ?>images/_tx_.gif" width="1" height="5"><br />
              <input type="button" id="sendMessage" name="submit" value="<?php echo $this->_lang['messages_send']; ?>" />
              <input type="button" name="cancel" value="<?php echo $this->_lang['cancel']; ?>" onClick="Etomite.loadPaneFromAction('myMessages');" />
            </span>
          </div>
    
        </fieldset>
      </form>
    </div>
</div>
<script type="text/javascript">
    $('#sendMessage').click(function() {
        Etomite.sendMyMessage();
    });
    $(document).ready(function() {
        $('#messages-tabs').tabs(
        <?php if ($composeFlag) {?>
        { selected: 2 }
        <?php } ?>
        );
    });
</script>