<div class="header"><?php echo $this->_lang['user_management_title']; ?></div>
<div id="users-tabs">
    <ul>
        <li><a href="#manage-users"><?php echo $this->_lang['user_management_title']; ?></a></li>
        <li><a href="#roles"><?php echo $this->_lang['role_management_title']; ?></a></li>
    </ul>
    <div id="manage-users">
        <div style="padding:5px 0;margin-bottom:10px;"><a href="javascript:;" id="newUser" class="button">New User</a></div>
        <p class="menuHeader"><?php echo $this->_lang['user_management_msg']; ?></p>
        <?php
          $sql = "select username, id from ".$this->db."manager_users order by username";
          $rs = $this->dbQuery($sql);
          $limit = $this->recordCount($rs);
          if($limit<1){
            echo "The request returned no users!</div>";
          } else {
              echo "<ul>";
              for($i=0; $i<$limit; $i++) {
                $row = $this->fetchRow($rs);
              ?>
                <li><a id="<?php echo $row['id']; ?>" class="userEditBtn"><?php echo $row['username']; ?></a></li>
              <?php
              }
              echo "</ul>";
          }
              ?>
        <script type="text/javascript">
            $('#newUser').click(function() {
                Etomite.editUser();
            });
            $('.userEditBtn').click(function() {
                Etomite.editUser($(this).attr('id'));
            });
        </script>
    </div>
    <div id="roles">
        <div style="padding:5px 0;margin-bottom:10px;"><a href="javascript:;" id="newRole" class="button">New Role</a></div>
        <p class="menuHeader"><?php echo $this->_lang['role_management_msg']; ?></p>
        <?php
          $sql = "select name, id, description from ".$this->db."user_roles order by name";
          $rs = $this->dbQuery($sql);
          $limit = $this->recordCount($rs);
          if($limit<1){
            echo "The request returned no roles!</div>";
          } else {
              echo "<ul>";
              for($i=0; $i<$limit; $i++) {
                $row = $this->fetchRow($rs);
                if($row['id']==1) {
              ?>
              <li><i><?php echo $row['name']; ?></i> - <i><?php echo $this->_lang['administrator_role_message']; ?></i></li>
              <?php
                } else {
              ?>
                <li><a id="<?php echo $row['id'];?>" class="editRoleBtn"><?php echo $row['name']; ?></a> - <?php echo $row['description']; ?></li>
              <?php
                }
              }
              echo "</ul>";
          }
              ?>
        <script type="text/javascript">
            $('#newRole').click(function() {
                Etomite.editRole();
            });
            $('.editRoleBtn').click(function() {
                Etomite.editRole($(this).attr('id'));
            });
        </script>
    </div>
</div>
<script type="text/javascript">
    $('#users-tabs').tabs();
</script>