<!DOCTYPE html>
<html>
    <head>
        <title><?php echo $etomite->config['full_appname'];?></title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <meta http-equiv="content-type" content="text/html; charset=<?php echo $etomite->config['etomite_charset']; ?>" />
		<meta name="robots" content="noindex, nofollow" />
        <!-- bootstrap 3.0.2 -->
        <link href="views/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <!-- font Awesome -->
        <link href="views/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <!-- Ionicons -->
        <link href="views/css/ionicons.min.css" rel="stylesheet" type="text/css" />
        <!-- Morris chart -->
        <link href="views/css/morris/morris.css" rel="stylesheet" type="text/css" />
        <!-- jvectormap -->
        <link href="views/css/jvectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet" type="text/css" />
        <!-- fullCalendar -->
        <link href="views/css/fullcalendar/fullcalendar.css" rel="stylesheet" type="text/css" />
        <!-- Daterange picker -->
        <link href="views/css/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
        <!-- bootstrap wysihtml5 - text editor -->
        <link href="views/css/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" rel="stylesheet" type="text/css" />
        <!-- Theme style -->
        <link href="views/css/AdminLTE.css" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js"></script> <!-- needed for el finder -->
       
        
        <!-- etoFork javascript -->
        <script src="./js/etomite.js" type="text/javascript"></script>
        <script src="./js/spin.min.js" type="text/javascript"></script>
		<script src="./js/functions.js" type="text/javascript"></script>
        
        <?php echo $etomite->langToJS();?>
        
        
        
        
        
        <!-- edit area -->
        <script type="text/javascript" src="./lib/editarea/edit_area_full.js"></script>
        
        <!-- etoFork init -->
		<?php $rel = (empty($strip_base_href)) ? "false" : "true"; ?>
        <script type="text/javascript">
		<!--//
			$(document).ready(function(){
				Etomite.EtoRoot = "<?php echo absolute_base_path; ?>";
				Etomite.rel = "<?php echo relative_base_path ?>";
				Etomite.db_url = "<?php echo www_base_path ?>";
				Etomite.cssPath = "<?php echo $cssPath; ?>";
				Etomite.dateFormat = "<?php echo $etomite->config['date_format']; ?>";
				Etomite.timeFormat = "<?php echo $etomite->config['$time_format']; ?>";
				Etomite.init();
			});
		//-->
		</script>
        
        <link rel="stylesheet" type="text/css" href="views/styles.css" />
        
		<?php $etomite->runSystemEvent("OnBeforeManagerHeadEnd"); ?>
    </head>
        <body class="skin-blue" id="adminbody">
        	<?php include_once('header.phtml'); ?>
            <div class="wrapper row-offcanvas row-offcanvas-left">
            <?php include_once('left_sidebar.phtml'); ?>
            <!-- Right side column. Main Content Area -->
            <aside class="right-side" id="mainContent">
            	<?php include_once('welcome.phtml'); ?>
            </aside>
            </div><!-- end wrapper -->
            <!-- Javascript Loads -->
            <!-- jQuery 2.0.2 -->
			<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
            
            <!-- jQuery UI 1.10.3 -->
            <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
            <!-- <script src="views/js/jquery-ui-1.10.3.min.js" type="text/javascript"></script> -->
            <script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
             
            <!-- style to override dialog -->
            <style type="text/css">
			.ui-front {
				z-index: 1000;
			}
			
			.no-close .ui-dialog-titlebar-close {
			display: none;
			}
			</style>
             
            <!-- time picker addon -->
            <script src="./js/jquery-ui-timepicker-addon.js" type="text/javascript"></script>
        
            <!-- Bootstrap -->
            <script src="views/js/bootstrap.min.js" type="text/javascript"></script>
            <!-- Morris.js charts --> <!-- not needed -->
            <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
            <script src="views/js/plugins/morris/morris.min.js" type="text/javascript"></script>
            <!-- Sparkline --> <!-- not needed -->
            <script src="views/js/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
            <!-- fullCalendar --> <!-- not needed -->
            <script src="views/js/plugins/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
            <!-- daterangepicker -->
            <script src="views/js/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
            <!-- Bootstrap WYSIHTML5 -->
            <script src="views/js/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js" type="text/javascript"></script>
            <!-- iCheck -->
            <script src="views/js/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    
            <!-- AdminLTE App -->
            <script src="views/js/AdminLTE/app.js" type="text/javascript"></script>
            <script src="views/js/AdminLTE/dashboard.js" type="text/javascript"></script>
            <?php
			if(debug) {
				var_dump($etomite->config);
			?>
			<script type="text/javascript">
			$(function() {
				Etomite.showDebugWindow();
			});
			</script>
			<?php
			}
			?>
            <!-- jqTree -->
            <link href="./lib/jqtree/jqtree.css" rel="stylesheet" />
            <script src="./lib/jqtree/tree.jquery.js"></script>
            <!-- contextMenu -->
            <script src="./lib/contextMenu/jquery.ui.position.js" type="text/javascript"></script>
    		<script src="./lib/contextMenu/jquery.contextMenu.js" type="text/javascript"></script>
        	<link href="./lib/contextMenu/jquery.contextMenu.css" rel="stylesheet" type="text/css" />
            
            <!-- Datatables --> <!-- may be removed in favor of bootstrap datatables -->
            <link href="./lib/datatables/css/demo_table_jui.css" media="screen" rel="stylesheet" type="text/css" />
            <script type="text/javascript" language="javascript" src="./lib/datatables/js/jquery.dataTables.min.js"></script>
            
            <!-- file manager -->
            <script src="views/js/jquery-migrate-1.2.1.min.js"></script>
            <!-- elFinder CSS (REQUIRED) -->
            <link rel="stylesheet" type="text/css" media="screen" href="./lib/elfinder2_0/css/elfinder.min.css">
            <link rel="stylesheet" type="text/css" media="screen" href="./lib/elfinder2_0/css/theme.css">
            
            <!-- elFinder JS (REQUIRED) -->
            <script type="text/javascript" src="./lib/elfinder2_0/js/elfinder.min.js"></script>
            <!--  end elFinder file manager -->
            
            
    	</body>
</html>