<?php
	if (isset($_SESSION['web_login_error']) && !empty($_SESSION['web_login_error'])) {
		$msg = "<p>".$msg."</p>";
		
		$error = "<p>".$_SESSION['web_login_error']."</p>";
		unset($_SESSION['web_login_error']);
	}
?>
<!DOCTYPE html>
<html class="skin-blue">
    <head>
        <title><?php echo $this->config['site_name'];?> - <?php echo $_lang["login"]; ?></title>
        <base href="<?php echo MANAGER_URL;?>" />
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <meta http-equiv="content-type" content="text/html; charset=<?php echo $etomite->config['etomite_charset']; ?>" />
		<meta name="robots" content="noindex, nofollow" />
        <!-- bootstrap 3.0.2 -->
        <link href="views/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <!-- font Awesome -->
        <link href="views/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <!-- Theme style -->
        <link href="views/css/AdminLTE.css" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        
        <!-- jQuery 2.0.2 -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <script src="./lib/contextMenu/jquery.ui.position.js" type="text/javascript"></script>
        <style type="text/css">
			.error { margin-top: 10px; }
		</style>
    </head>
    <body class="skin-blue" id="loginPage">
		<form method="post" name="web_login" action="<?php echo www_base_path;?>?web_login=1&amp;login_redirect=<?php echo urlencode($url);?>">
        <div class="form-box" id="login-box">
            <div class="header">
            <img src='./images/misc/etofork_logo.png' alt='<?php echo $release; ?>' title='<?php echo $release; ?>' /><br />
            Sign In
            </div>
                <div class="body bg-gray">
                	<?php if (!empty($error)) { ?>
                	<div class="error alert alert-danger"><?php echo $msg.$error;?></div>
                    <?php } ?>
                    <div class="form-group">
                        <input type="text" name="username" id="username" class="form-control" placeholder="<?php echo $_lang["username"]; ?>"/>
                    </div>
                    <div class="form-group">
                        <input type="password" name="password" id="password" class="form-control" placeholder="<?php echo $_lang["password"]; ?>"/>
                    </div>          
                    <div class="form-group">
                        <input type="checkbox" name="remember_me"/> Remember me
                    </div>
                </div>
                <div class="footer">                                                               
                    <button type="submit" id="loginBtn" class="btn bg-olive btn-block">Sign me in</button>  
                    
                    <!-- <p><a href="#">I forgot my password</a></p> -->
                </div>
            <div align="center"><p><?php echo $_lang["copy_msg"]; ?></p></div>
        </div>
		</form>
        <!-- Bootstrap -->
        <script src="views/js/bootstrap.min.js" type="text/javascript"></script>        

    </body>
</html>