		<!-- header logo: style can be found in header.less -->
        <header class="header">
            <a href="./" class="logo">
                <!-- Add the class icon to your logo image or logo icon to add the margining -->
                <img src="./images/misc/etofork_logo_sm.png" alt="etoFork CMS" alt="<?php echo $etomite->config['full_appname'];?>" />
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-right">
                    <ul class="nav navbar-nav">
                        <!-- Messages: style can be found in dropdown.less-->
                        <?php if($_SESSION['permissions']['messages']==1) { ?>
                        <li class="dropdown messages-menu hidden-xs">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-envelope"></i>
                                <span class="label label-success"><?php echo isset($_SESSION['nrnewmessages']) ? $_SESSION['nrnewmessages'] : 0; ?></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="header">You have <?php echo isset($_SESSION['nrnewmessages']) ? $_SESSION['nrnewmessages'] : 0; ?> new messages</li>
                                <?php
								$sql = "SELECT * FROM ".$etomite->db."user_messages WHERE ".$etomite->db."user_messages.recipient=".$_SESSION['internalKey']." ORDER BY postdate DESC LIMIT 0,10";
      							$rs = $etomite->dbQuery($sql);
								$limit = $etomite->recordCount($rs);
								if ($limit > 0) {
								?>
                                <li>
                                    <!-- inner menu: contains the actual data -->
                                    <ul class="menu">
                                        <?php while ($message = $etomite->fetchRow($rs)) { 
											$sender = $message['sender'];
											if($sender==0) {
											  $sendername = "[System]";
											} else {
											  $sql = "SELECT username FROM ".$etomite->db."manager_users WHERE id=$sender";
											  $rs2 = $etomite->dbQuery($sql);
											  $row2 = $etomite->fetchRow($rs2);
											  $sendername = $row2['username'];
											}
										?>
                                        <li><!-- start message -->
                                            <a href="javascript:;" onClick="Etomite.myMessages('id=<?php echo $message['id']; ?>&m=r');">
                                                <h4>
                                                    <?php echo $sendername; ?>
                                                </h4>
                                                <p><?php echo $message['subject']; ?></p>
                                            </a>
                                        </li><!-- end message -->
                                        <?php } // end while ?>
                                    </ul>
                                </li>
                                <?php } // end if ?>
                                <li class="footer"><a href="javascript:;" onclick="Etomite.myMessages();">See All Messages</a></li>
                            </ul>
                        </li>
                        <?php } ?>
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="glyphicon glyphicon-user"></i>
                                <span><?php echo $_SESSION['fullname']; ?> <i class="caret"></i></span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header bg-light-blue">
                                    <img src="views/img/avatar5.png" class="img-circle" alt="User Image" />
                                    <p>
                                        <?php echo $_SESSION['fullname']; ?>
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="javascript:;" onclick="Etomite.editUser('<?php echo $_SESSION['internalKey'];?>');" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="./?logout=1" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>