<div class="header">Install a Module</div>
<div class="content">
    <p>This form installs a new module to the system.<br />The module must be in the /tmp/packages folder and be in the format of a .tgz file<br />
    The packages folder must be writable by the system, the module file and the /modules folder.<br />
    <p>Enter the name of the module in the text box below to install a new module! (The name entered here is the first part of the package file. example: mod_test.tgz, you would enter mod_test)</p>
    <p><input type="text" name="module" id="module_name" value="" /> &nbsp; <a href="#" class="install-module-btn button">Install</a></p>

</div>