<div class="header"><?php echo $etomite->_lang['manage_modules']; ?></div>
<div id="module-manager-tabs">
    <ul>
        <li><a href="#module-list"><?php echo $etomite->_lang['modules_list']; ?></a></li>
        <li><a href="#install-module"><?php echo $etomite->_lang["modules_install_new"]; ?></a></li>
    </ul>
    <div id="module-list"><?php $this->listModules();?></div>
    <div id="install-module">
        <?php echo $this->_lang["module_install_msg"]; ?>
        <p><strong><?php echo $this->_lang["module"]; ?>:</strong> <input type="text" name="module" id="module_name" value="" /> &nbsp; <a href="#" class="install-module-btn button"><?php echo $this->_lang["install"]; ?></a></p>
        <p>&nbsp;</p>
        <div id="fileManager"></div>
    </div>
</div>
<script type="text/javascript">
	$('#module-manager-tabs').tabs();
</script>