<section class="content-header">
    <h1>
        Manage Files
    </h1>
    <ol class="breadcrumb">
        <li><a href="./"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li class="active"><i class="fa fa-user"></i> Manage Files</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
	<div id="fileManager"></div>
	<script type="text/javascript">
    setTimeout(function() {
        var elf = $('#fileManager').elfinder({
            lang: 'en',             // language (OPTIONAL)
            url : './lib/elfinder2_0/php/connector.php',  // connector URL (REQUIRED)
            height: 600,
            contextmenu : {
             // navbarfolder menu
             navbar :
               ['open', '|', 'copy', 'cut', 'paste', 'duplicate', '|', 'rm', '|', 'info'],
             // current directory menu
             cwd    :
               ['reload', 'back', '|', 'upload', 'mkdir', 'mkfile', 'paste', '|', 'info'],
             // current directory file menu
             files  :
               ['getfile', '|','open', 'quicklook', '|', 'download', '|', 'copy', 'cut', 'paste', 'duplicate', '|', 'rm', '|', 'edit', 'rename', 'resize', '|', 'archive', 'extract', '|', 'info']
             },
             customData : {token : '427820038402jfkals89802', inManager : 'true'},
             commands : [
                        'open', 'reload', 'home', 'up', 'back', 'forward', 'getfile', 'quicklook',
                        'download', 'rm', 'duplicate', 'rename', 'mkdir', 'mkfile', 'upload', 'copy',
                        'cut', 'paste', 'edit', 'resize', 'extract', 'archive', 'search', 'info', 'view', 'help'
                    ]
        }).elfinder('instance');
    }, 1000);
    
    </script>
</section>

