<!DOCTYPE html>
<html>
<head>
<title><?php echo $etomite->config['full_appname'];?></title>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.min.css" />
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js"></script>
<script src="http://code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.min.js"></script>
<script type="text/javascript" src="./js/etomite.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        Etomite.inAdmin = false;
        Etomite.isMobile = true;
        Etomite.init();
    });
</script>
</head>
<body>
    <div data-role="page">
        <div data-role="header"><h1><?php echo $etomite->config['full_appname'];?> - Login</h1></div>
        <div data-role="content">
            <div class="error"></div>
            <div class="success"></div>
            <div data-role="fieldcontain" class="ui-hide-label">
                <label for="username">Username:</label>
                <input type="text" name="username" id="username" value="" placeholder="Username"/>
            </div>
            <div data-role="fieldcontain" class="ui-hide-label">
                <label for="username">Password:</label>
                <input type="password" name="password" id="password" value="" placeholder="Password"/>
            </div>
            <div data-role="fieldcontain">
                <input type="checkbox" name="licenseOK" id="licenseOK" checked='checked' />
                <label for="licenseOK">&quot;I agree to use Etomite in Accordance with the GPL.&quot;</label>
            </div>
            <button value="submit-value" id="loginBtn" name="submit" data-theme="b" type="submit" class="ui-btn-hidden" aria-disabled="false">Login</button>
        </div>
    </div>
</body>
</html>