<section class="content-header">
    <h1>
        <?php echo $this->_lang['move_document_title']; ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="./"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li class="active"><i class="fa fa-arrows"></i> <?php echo $this->_lang['move_document_title']; ?></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
	<div class="box box-primary">
        <div class="box-header">
            <i class="fa fa-group"></i>
            <h3 class="box-title"><?php echo $this->_lang['move_document_title']; ?></h3>
        </div>
        <div class="box-body">
        	<p><?php echo $this->_lang['move_document_message']; ?></p>
        </div>
    </div>
</section>
