<div class="header"><?php echo $this->_lang['resource_management']; ?></div>
<div id="resource-tabs">
    <ul>
        <?php if ($this->checkUserRole('new_template', $_SESSION['internalKey']) || $this->checkUserRole('edit_template', $_SESSION['internalKey'])) { ?>
        <li><a href="#templates"><?php echo $this->_lang['manage_templates']; ?></a></li>
        <?php }?>
        <?php if ($this->checkUserRole('new_snippet', $_SESSION['internalKey']) || $this->checkUserRole('edit_snippet', $_SESSION['internalKey'])) { ?>
        <li><a href="#snippets"><?php echo $this->_lang['manage_snippets']; ?></a></li>
        <?php } ?>
        <?php if ($this->checkUserRole('new_chunk', $_SESSION['internalKey']) || $this->checkUserRole('edit_chunk', $_SESSION['internalKey'])) { ?>
        <li><a href="#chunks"><?php echo $this->_lang['manage_htmlsnippets']; ?></a></li>
        <?php } ?>
        <li><a href="#templateVars"><?php echo $this->_lang['template_var_tab']; ?></a></li>
        <li><a href="#categories"><?php echo $this->_lang['manage_categories']; ?></a></li>
    </ul>
    <?php if ($this->checkUserRole('new_template', $_SESSION['internalKey']) || $this->checkUserRole('edit_template', $_SESSION['internalKey'])) { ?>
    <div id="templates">
        <?php if ($this->checkUserRole('new_template', $_SESSION['internalKey'])) { ?>
        <div style="padding:5px 0;margin-bottom:10px;"><a href="javascript:;" id="newTemplate" class="button">New Template</a></div>
        <?php } ?>
        <p><?php echo $this->_lang['template_management_msg']; ?></p>
        <?php
            $sql = "select templatename, id, description, locked from ".$this->db."site_templates order by templatename";
            $rs = $this->dbQuery($sql);
            $limit = $this->recordCount($rs);
            if($limit<1){
              echo "<p>".$this->_lang['no_results']."</p>";
            } else {
                echo "<ul>";
                for($i=0; $i<$limit; $i++) {
                    $row = $this->fetchRow($rs);
                    $id = strval($row['id']);
        ?>
        <li><a id="<?php echo $row['id'];?>" class="templateBtn"><?php echo $row['templatename']; ?></a> (<?php echo $row['id']; ?>)<?php echo $row['description']!='' ? ' - '.$row['description'] : '' ; ?><?php echo $row['locked']==1 ? ' <i><small>('.$this->_lang['template_locked_message'].')</small></i>' : "" ; ?></li>
        <?php
                }// end for
            }// end else for limit
        ?>
        <script type="text/javascript">
            <?php if ($this->checkUserRole('new_template', $_SESSION['internalKey'])) { ?>
            $('#newTemplate').click(function() {
                Etomite.editResource('template');
            });
            <?php } ?>
            <?php if ($this->checkUserRole('edit_template', $_SESSION['internalKey'])) { ?>
            $('.templateBtn').click(function() {
                Etomite.editResource('template', $(this).attr('id'));
            });
            <?php } ?>
        </script>
    </div>
    <?php } ?>
    <?php if ($this->checkUserRole('new_snippet', $_SESSION['internalKey']) || $this->checkUserRole('edit_snippet', $_SESSION['internalKey'])) { ?>
    <div id="snippets">
        <?php if ($this->checkUserRole('new_snippet', $_SESSION['internalKey'])) { ?>
        <div style="padding:5px 0;margin-bottom:10px;"><a href="javascript:;" id="newSnippet" class="button">New Snippet</a></div>
        <?php } ?>
        <p><?php echo $this->_lang['snippet_management_msg']; ?></p>
        <div id="snippet-accordion">
        <?php
            // modified 2010-04-22 by John Carlson to add section function and organizaion of snippets
            $sqlS = "select * from ".$this->db."site_section order by sort_order DESC,name ASC";
            $rsS = $this->dbQuery($sqlS);
            $limitS = $this->recordCount($rsS);
            if($limitS<1){
                echo $_lang['no_results'];
            }
            for($z=0;$z<$limitS;$z++){
                $rowS = $this->fetchRow($rsS);
                
                // build box
            ?>
            
            <?php
            // start snippets
                  $sql = "select name, id, description, locked from ".$this->db."site_snippets where section=".$rowS['id']." order by name";
                  $rs = $this->dbQuery($sql);
                  $limit = $this->recordCount($rs);
                  if($limit<1){
                    echo $_lang['no_results'];
                  }else {
                  ?>
                  <h3><a href="#"><?php echo $rowS['name']." - ".$rowS['description']; ?></a></h3>
            <div>
                  <?php
                  echo "<ul>";
                  for($i=0; $i<$limit; $i++) {
                    $row = $this->fetchRow($rs);
                ?>
                
                    <li><a id="<?php echo $row['id'];?>" class="snippetBtn">
                        <?php echo $row['name']; ?>
                      </a>
                      <?php echo $row['description']!='' ? ' - '.$row['description'] : '' ; ?>
                      <?php echo $row['locked']==1 ? ' <i><small>('.$_lang['snippet_locked_message'].')</small></i>' : "" ; ?>
                    </li>
        
        <?php
            
                    } // end for for snippets
                    echo "</ul></div>";
                  }// end if for limit
                    // end snippets
          }// end for for sections
          
        ?>
            <h3><a href="#">Un-categorized</a></h3>
            <div>
                <?php
                $sql = "select name, id, description, locked from ".$this->db."site_snippets where section<1 order by name";
                  $rs = $this->dbQuery($sql);
                  $limit = $this->recordCount($rs);
                  if($limit<1){
                    echo $_lang['no_results'];
                  }
                  echo "<ul>";
                  for($i=0; $i<$limit; $i++) {
                    $row = $this->fetchRow($rs);
                ?>
                
                    <li><a id="<?php echo $row['id'];?>" class="snippetBtn">
                        <?php echo $row['name']; ?>
                      </a>
                      <?php echo $row['description']!='' ? ' - '.$row['description'] : '' ; ?>
                      <?php echo $row['locked']==1 ? ' <i><small>('.$_lang['snippet_locked_message'].')</small></i>' : "" ; ?>
                    </li>
        
                  <?php
            
                    } // end for for snippets
                    echo "</ul>";
                  ?>
              </div>
        </div>
        <script type="text/javascript">
            <?php if ($this->checkUserRole('new_snippet', $_SESSION['internalKey'])) { ?>
            $('#newSnippet').click(function() {
                Etomite.editResource('snippet');
            });
            <?php } ?>
            <?php if ($this->checkUserRole('edit_snippet', $_SESSION['internalKey'])) { ?>
            $('.snippetBtn').click(function() {
                Etomite.editResource('snippet', $(this).attr('id'));
            });
            <?php } ?>
            $('#snippet-accordion').accordion({fillSpace: true, clearStyle: true});
        </script>
    </div>
    <?php } ?>
    <?php if ($this->checkUserRole('new_chunk', $_SESSION['internalKey']) || $this->checkUserRole('edit_chunk', $_SESSION['internalKey'])) { ?>
    <div id="chunks">
        <?php if ($this->checkUserRole('new_chunk', $_SESSION['internalKey'])) { ?>
        <div style="padding:5px 0;margin-bottom:10px;"><a href="javascript:;" id="newChunk" class="button">New Chunk</a></div>
        <?php } ?>
        <p><?php echo $this->_lang['htmlsnippet_management_msg']; ?></p>
        <div id="chunk-accordion">
        <?php
            // modified 2010-04-22 by John Carlson to add section function and organizaion of snippets
            $sqlS = "select * from ".$this->db."site_section order by sort_order DESC,name ASC";
            $rsS = $this->dbQuery($sqlS);
            $limitS = $this->recordCount($rsS);
            if($limitS<1){
                echo $_lang['no_results'];
            }
            for($z=0;$z<$limitS;$z++){
                $rowS = $this->fetchRow($rsS);
                
                // build box
            ?>
            
        <?php
            // start chunks
            $sql = "select name, id, description, locked from ".$this->db."site_htmlsnippets where section=".$rowS['id']." order by name";
            $rs = $this->dbQuery($sql);
            $limit = $this->recordCount($rs);
            if($limit<1){
              echo $_lang['no_results'];
            } else {
            ?>
            <h3><a href="#"><?php echo $rowS['name']." - ".$rowS['description']; ?></a></h3>
            <div>
            <?php
            echo "<ul>";
            for($i=0; $i<$limit; $i++) {
              $row = $this->fetchRow($rs);
        ?>
              <li>
                <a class="chunkBtn" id="<?php echo $row['id'];?>"><?php echo $row['name']; ?></a>
                <?php echo $row['description']!='' ? ' - '.$row['description'] : '' ; ?><?php echo $row['locked']==1 ? ' <i><small>('.$_lang['snippet_locked_message'].')</small></i>' : "" ; ?>
              </li>
        <?php
            } // end for for chunks
            echo "</ul></div>";
            }// end if for limit
          }// end for for sections
        ?>
            <h3><a href="#">Un-categorized</a></h3>
            <div>
                <?php
                $sql = "select name, id, description, locked from ".$this->db."site_htmlsnippets where section<1 order by name";
                  $rs = $this->dbQuery($sql);
                  $limit = $this->recordCount($rs);
                  if($limit<1){
                    echo $_lang['no_results'];
                  }
                  echo "<ul>";
                  for($i=0; $i<$limit; $i++) {
                    $row = $this->fetchRow($rs);
                ?>
                
                    <li><a id="<?php echo $row['id'];?>" class="chunkBtn">
                        <?php echo $row['name']; ?>
                      </a>
                      <?php echo $row['description']!='' ? ' - '.$row['description'] : '' ; ?>
                      <?php echo $row['locked']==1 ? ' <i><small>('.$_lang['snippet_locked_message'].')</small></i>' : "" ; ?>
                    </li>
        
                  <?php
            
                    } // end for for snippets
                    echo "</ul>";
                  ?>
              </div>
        </div>
        <script type="text/javascript">
            <?php if ($this->checkUserRole('new_chunk', $_SESSION['internalKey'])) { ?>
            $('#newChunk').click(function() {
                Etomite.editResource('chunk');
            });
            <?php } ?>
            <?php if ($this->checkUserRole('edit_chunk', $_SESSION['internalKey'])) { ?>
            $('.chunkBtn').click(function() {
                Etomite.editResource('chunk', $(this).attr('id'));
            });
            <?php } ?>
            $('#chunk-accordion').accordion({fillSpace: true, clearStyle: true});
        </script>
    </div>
    <?php } ?>
    <?php if ($this->checkUserRole('new_tv', $_SESSION['internalKey']) || $this->checkUserRole('edit_tv', $_SESSION['internalKey'])) { ?>
    <div id="templateVars">
        <div style="padding:5px 0;margin-bottom:10px;"><a href="javascript:;" id="newTv" class="button"><?php echo $this->_lang['create_template_var'];?></a></div>
        <p><?php echo $this->_lang['template_var_tab_msg'];?></p>
        <?php
            $tvs = $this->getIntTableRows($fields="tv_id,field_name,name,description",$from="template_variables");
            if (count($tvs) > 0) {
            ?>
                <ul>
                    <?php foreach($tvs as $tv) {?>
                        <li><a id="<?php echo $tv['tv_id'];?>" class="tvBtn"><?php echo $tv['name']." (".$tv['field_name'].") - ".$tv['description'];?></a></li>
                    <?php }?>
                </ul>
            <?php
            } else {
                echo "<p><em>Currently no Template Variables!</em></p>";
            }
        ?>
        <script type="text/javascript">
            <?php if ($this->checkUserRole('new_chunk', $_SESSION['internalKey'])) { ?>
            $('#newTv').click(function() {
                Etomite.editTV();
            });
            <?php } ?>
            <?php if ($this->checkUserRole('edit_chunk', $_SESSION['internalKey'])) { ?>
            $('.tvBtn').click(function() {
                Etomite.editTV($(this).attr('id'));
            });
            <?php } ?>
        </script>
    </div>
    <?php } ?>
    <div id="categories">
        <div style="padding:5px 0;margin-bottom:10px;"><a href="javascript:;" id="newCategory" class="button">New Category</a></div>
        <p><?php echo $this->_lang['category_management_msg']; ?></p>
        <?php
            $sql = "select name, id, description from ".$this->db."site_section order by name ASC";
            $rs = $this->dbQuery($sql);
            $limit = $this->recordCount($rs);
            if($limit<1){
              echo "<p>".$this->_lang['no_results']."</p>";
            } else {
                echo "<ul>";
                for($i=0; $i<$limit; $i++) {
                    $row = $this->fetchRow($rs);
                    $id = strval($row['id']);
        ?>
        <li><a id="<?php echo $row['id'];?>" class="categoryBtn"><?php echo $row['name']; ?></a> (<?php echo $row['id']; ?>)<?php echo $row['description']!='' ? ' - '.$row['description'] : '' ; ?></li>
        <?php
                }// end for
            }// end else for limit
        ?>
        <script type="text/javascript">
            $('#newCategory').click(function() {
                Etomite.createSection();
            });
            /*$('.categoryBtn').click(function() {
                Etomite.editResource('template', $(this).attr('id'));
            });*/
        </script>
    </div>
</div>

<script type="text/javascript">
    $('#resource-tabs').tabs({
        selected: Etomite.resourceTabSelected,
        select: function(event, ui) {
            Etomite.resourceTabSelected = ui.index;
        }
    });
</script>