<div class="header"><?php echo $this->_lang['resource_management']; ?></div>
<div id="resource-tabs">
    <ul>
        <li><a href="#templates"><?php echo $this->_lang['manage_templates']; ?></a></li>
        <li><a href="#snippets"><?php echo $this->_lang['manage_snippets']; ?></a></li>
        <li><a href="#chunks"><?php echo $this->_lang['manage_htmlsnippets']; ?></a></li>
        <li><a href="#templateVars"><?php echo $this->_lang['template_var_tab'];?></a></li>
    </ul>
    <div id="templates">
        <div style="padding:5px 0;margin-bottom:10px;"><a href="javascript:;" id="newTemplate" class="button">New Template</a></div>
        <p><?php echo $this->_lang['template_management_msg']; ?></p>
        <?php
            $sql = "select templatename, id, description, locked from ".$this->db."site_templates order by templatename";
            $rs = $this->dbQuery($sql);
            $limit = $this->recordCount($rs);
            if($limit<1){
              echo "<p>".$this->_lang['no_results']."</p>";
            } else {
                echo "<ul>";
                for($i=0; $i<$limit; $i++) {
                    $row = $this->fetchRow($rs);
                    $id = strval($row['id']);
        ?>
        <li><a id="<?php echo $row['id'];?>" class="templateBtn"><?php echo $row['templatename']; ?></a> (<?php echo $row['id']; ?>)<?php echo $row['description']!='' ? ' - '.$row['description'] : '' ; ?><?php echo $row['locked']==1 ? ' <i><small>('.$this->_lang['template_locked_message'].')</small></i>' : "" ; ?></li>
        <?php
                }// end for
            }// end else for limit
        ?>
        <script type="text/javascript">
            $('#newTemplate').click(function() {
                Etomite.editResource('template');
            });
            $('.templateBtn').click(function() {
                Etomite.editResource('template', $(this).attr('id'));
            });
        </script>
    </div>
    
    <div id="snippets">
        <div style="padding:5px 0;margin-bottom:10px;"><a href="javascript:;" id="newSnippet" class="button">New Snippet</a><a href="javascript:;" id="newSnippetSection" class="button">New Section</a></div>
        <p><?php echo $this->_lang['snippet_management_msg']; ?></p>
        <div id="snippet-accordion">
        <?php
            // modified 2010-04-22 by John Carlson to add section function and organizaion of snippets
            $sqlS = "select * from ".$this->db."site_section where section_type='snippet' order by sort_order DESC,name ASC";
            $rsS = $this->dbQuery($sqlS);
            $limitS = $this->recordCount($rsS);
            if($limitS<1){
                echo $_lang['no_results'];
            }
            for($z=0;$z<$limitS;$z++){
                $rowS = $this->fetchRow($rsS);
                
                // build box
            ?>
            <h3><a href="#"><?php echo $rowS['name']." - ".$rowS['description']; ?></a></h3>
            <div>
            <?php
            // start snippets
                  $sql = "select name, id, description, locked from ".$this->db."site_snippets where section=".$rowS['id']." order by name";
                  $rs = $this->dbQuery($sql);
                  $limit = $this->recordCount($rs);
                  if($limit<1){
                    echo $_lang['no_results'];
                  }
                  echo "<ul>";
                  for($i=0; $i<$limit; $i++) {
                    $row = $this->fetchRow($rs);
                ?>
                
                    <li><a id="<?php echo $row['id'];?>" class="snippetBtn">
                        <?php echo $row['name']; ?>
                      </a>
                      <?php echo $row['description']!='' ? ' - '.$row['description'] : '' ; ?>
                      <?php echo $row['locked']==1 ? ' <i><small>('.$_lang['snippet_locked_message'].')</small></i>' : "" ; ?>
                    </li>
        
        <?php
            
                    } // end for for snippets
                    echo "</ul></div>";
                    
                    // end snippets
          }// end for for sections
        ?>
        </div>
        <script type="text/javascript">
            $('#newSnippet').click(function() {
                Etomite.editResource('snippet');
            });
            $('#newSnippetSection').click(function() {
                Etomite.createSection('snippet');
            });
            $('.snippetBtn').click(function() {
                Etomite.editResource('snippet', $(this).attr('id'));
            });
            $('#snippet-accordion').accordion({fillSpace: true, clearStyle: true});
        </script>
    </div>
    
    <div id="chunks">
        <div style="padding:5px 0;margin-bottom:10px;"><a href="javascript:;" id="newChunk" class="button">New Chunk</a><a href="javascript:;" id="newChunkSection" class="button">New Section</a></div>
        <p><?php echo $this->_lang['htmlsnippet_management_msg']; ?></p>
        <div id="chunk-accordion">
        <?php
            // modified 2010-04-22 by John Carlson to add section function and organizaion of snippets
            $sqlS = "select * from ".$this->db."site_section where section_type='chunk' order by sort_order DESC,name ASC";
            $rsS = $this->dbQuery($sqlS);
            $limitS = $this->recordCount($rsS);
            if($limitS<1){
                echo $_lang['no_results'];
            }
            for($z=0;$z<$limitS;$z++){
                $rowS = $this->fetchRow($rsS);
                
                // build box
            ?>
            <h3><a href="#"><?php echo $rowS['name']." - ".$rowS['description']; ?></a></h3>
            <div>
        <?php
            // start chunks
            $sql = "select name, id, description, locked from ".$this->db."site_htmlsnippets where section=".$rowS['id']." order by name";
            $rs = $this->dbQuery($sql);
            $limit = $this->recordCount($rs);
            if($limit<1){
              echo $_lang['no_results'];
            }
            echo "<ul>";
            for($i=0; $i<$limit; $i++) {
              $row = $this->fetchRow($rs);
        ?>
              <li>
                <a class="chunkBtn" id="<?php echo $row['id'];?>"><?php echo $row['name']; ?></a>
                <?php echo $row['description']!='' ? ' - '.$row['description'] : '' ; ?><?php echo $row['locked']==1 ? ' <i><small>('.$_lang['snippet_locked_message'].')</small></i>' : "" ; ?>
              </li>
        <?php
            } // end for for chunks
            echo "</ul></div>";
          }// end for for sections
        ?>
        </div>
        <script type="text/javascript">
            $('#newChunk').click(function() {
                Etomite.editResource('chunk');
            });
            $('#newChunkSection').click(function() {
                Etomite.createSection('chunk');
            });
            $('.chunkBtn').click(function() {
                Etomite.editResource('chunk', $(this).attr('id'));
            });
            $('#chunk-accordion').accordion({fillSpace: true, clearStyle: true});
        </script>
    </div>
    <div id="templateVars">
        <div style="padding:5px 0;margin-bottom:10px;"><a href="javascript:;" id="newTv" class="button"><?php echo $this->_lang['create_template_var'];?></a></div>
        <p><?php echo $this->_lang['template_var_tab_msg'];?></p>
        <?php
            $tvs = $this->getIntTableRows($fields="tv_id,field_name,name,description",$from="template_variables");
            if (count($tvs) > 0) {
            ?>
                <ul>
                    <?php foreach($tvs as $tv) {?>
                        <li><a id="<?php echo $tv['tv_id'];?>" class="tvBtn"><?php echo $tv['name']." (".$tv['field_name'].") - ".$tv['description'];?></a></li>
                    <?php }?>
                </ul>
            <?php
            } else {
                echo "<p><em>Currently no Template Variables!</em></p>";
            }
        ?>
        <script type="text/javascript">
            $('#newTv').click(function() {
                Etomite.editTV();
            });
            $('.tvBtn').click(function() {
                Etomite.editTV($(this).attr('id'));
            });
        </script>
    </div>
</div>

<script type="text/javascript">
    $('#resource-tabs').tabs({
        selected: Etomite.resourceTabSelected,
        select: function(event, ui) {
            Etomite.resourceTabSelected = ui.index;
        }
    });
</script>