<section class="content-header">
    <h1>
        <?php echo $this->_lang['settings_title']; ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="./"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li class="active"><i class="fa fa-user"></i> <?php echo $this->_lang['settings_title']; ?></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
	<div class="action-btns">
        <a href="javascript:;" id="saveSystemSettings" class="btn btn-success"><?php echo $this->_lang['save']; ?></a>
        <a href="javascript:;" id="cancelSystemSettings" class="btn btn-warning"><?php echo $this->_lang['cancel']; ?></a>
    </div>
    <form name="system-settings-form" id="system-settings-form">
    <div class="nav-tabs-custom">
        <!-- Tabs within a box -->
        <ul class="nav nav-tabs">
            <li class="active"><a href="#site_settings" data-toggle="tab"><?php echo $this->_lang["settings_site"] ?></a></li>
            <li><a href="#furl_settings" data-toggle="tab"><?php echo $this->_lang["settings_furls"] ?></a></li>
            <li><a href="#user_system_settings" data-toggle="tab"><?php echo $this->_lang["settings_users"] ?></a></li>
            <li><a href="#ui_settings" data-toggle="tab"><?php echo $this->_lang["settings_ui"] ?></a></li>
            <li><a href="#misc_settings" data-toggle="tab"><?php echo $this->_lang["settings_misc"] ?></a></li>
        </ul>
        <div class="tab-content">
        	<div class="tab-pane active" id="site_settings" style="position: relative;">
            	<?php include_once('site_settings.phtml');?>
            </div>
            <div class="tab-pane" id="furl_settings" style="position: relative;">
            	<?php include_once('furl_settings.phtml');?>
            </div>
            <div class="tab-pane" id="user_system_settings" style="position: relative;">
            	<?php include_once('user_system_settings.phtml');?>
            </div>
            <div class="tab-pane" id="ui_settings" style="position: relative;">
            	<?php include_once('ui_settings.phtml');?>
            </div>
        	<div class="tab-pane" id="misc_settings" style="position: relative;">
            	<?php include_once('misc_settings.phtml');?>
            </div>
        </div><!-- end tab content -->
    </div><!-- end tabs -->
    </form>
</section>

<script type="text/javascript">
$(document).ready(function(){
    $('#saveSystemSettings').click(function() {
        Etomite.saveSiteSettings();
    });
    $('#cancelSystemSettings').click(function() {
        Etomite.loadPaneFromAction('loadWelcome');
    });
});
</script>