<div class="header"><?php echo $this->_lang['user_management_title']; ?></div>
<div id="users-tabs">
    <ul>
        <li><a href="#manage-users"><?php echo $this->_lang['user_management_title']; ?></a></li>
        <li><a href="#roles"><?php echo $this->_lang['role_management_title']; ?></a></li>
    </ul>
    <div id="manage-users">
        <div style="padding:5px 0;margin-bottom:10px;"><a href="javascript:;" id="newUser" class="button"><?php echo $this->_lang['new_user']; ?></a></div>
        <p class="menuHeader"><?php echo $this->_lang['user_management_msg']; ?></p><p>&nbsp;</p>
          <table width="100%" cellpadding="0" cellspacing="0" border="0" class="display" id="user-tbl">
          <thead>
          	<tr>
            	<th>User ID</th>
                <th>Username</th>
                <th>Name</th>
                <th>Email</th>
            </tr>
          </thead>
          <tbody>
          <?php
		  $users = $this->getUsers();
		  foreach($users as $u) {
			?>
            <tr>
            	<td><?php echo $u['id'];?></td>
                <td><a id="<?php echo $u['id']; ?>" class="userEditBtn"><?php echo $u['username'];?></a></td>
                <td><?php echo $u['fullname'];?></td>
                <td><?php echo $u['email'];?></td>
            </tr>
            <?php  
		  }
              ?>
              </tbody>
          </table>
        <script type="text/javascript">
            $('#newUser').click(function() {
                Etomite.editUser();
            });
            $('.userEditBtn').click(function() {
                Etomite.editUser($(this).attr('id'));
            });
			oTable = $('#user-tbl').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});
        </script>
    </div>
    <div id="roles">
        <div style="padding:5px 0;margin-bottom:10px;"><a href="javascript:;" id="newRole" class="button">New Role</a></div>
        <p class="menuHeader"><?php echo $this->_lang['role_management_msg']; ?></p><p>&nbsp;</p>
        <table width="100%" cellpadding="0" cellspacing="0" border="0" class="display" id="row-tbl">
          <thead>
          	<tr>
            	<th>Role ID</th>
                <th>Role</th>
                <th>Description</th>
            </tr>
          </thead>
          <tbody>
        <?php
          $sql = "select name, id, description from ".$this->db."user_roles order by name";
          $rs = $this->dbQuery($sql);
          $limit = $this->recordCount($rs);
			  
              for($i=0; $i<$limit; $i++) {
                $row = $this->fetchRow($rs);
				?>
                <tr>
              <?php
                if($row['id']==1) {
              ?>
              <td><?php echo $row['id'];?></td>
              <td><i><?php echo $row['name']; ?></i></td>
              <td><i><?php echo $this->_lang['administrator_role_message']; ?></i></td>
              <?php
                } else {
              ?>
              	<td><?php echo $row['id'];?></td>
                <td><a id="<?php echo $row['id'];?>" class="editRoleBtn"><?php echo $row['name']; ?></a></td>
                <td><?php echo $row['description']; ?></td>
              <?php
                }
				?>
                </tr>
              <?php
              }
              ?>
           </tbody>
         </table>
        <script type="text/javascript">
            $('#newRole').click(function() {
                Etomite.editRole();
            });
            $('.editRoleBtn').click(function() {
                Etomite.editRole($(this).attr('id'));
            });
			roTable = $('#row-tbl').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});
        </script>
    </div>
</div>
<script type="text/javascript">
    $('#users-tabs').tabs();
</script>