<?php include_once("./includes/config_check.inc.php"); ?>
<section class="content-header">
    <h1>
        Dashboard
        <small>Welcome</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="./"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
	<!-- top row used for sortable-->
    <div class="row">
        <div class="col-xs-12 connectedSortable">
            
        </div><!-- /.col -->
    </div>
    <!-- /.row -->
	<div class="row">
        <!-- Left col -->
        <section class="col-lg-6 connectedSortable">
        	<!-- welcome message and logs -->
        	<div class="box box-primary">
                <div class="box-header">
                    <!-- tools box -->
                    <div class="pull-right box-tools">
                        <button class="btn btn-primary btn-sm pull-right" data-widget='collapse' data-toggle="tooltip" title="Collapse" style="margin-right: 5px;"><i class="fa fa-minus"></i></button>
                    </div><!-- /. tools -->
    
                    <i class="fa fa-cloud"></i>
                    <h3 class="box-title">
                        <?php echo $_lang["welcome_title"]; ?>
                    </h3>
                </div>
                <div class="box-body">
                <?php include_once('welcome_logs.phtml'); ?>
                </div>
            </div><!-- /.end box --><!-- end welcome logs -->
            <!-- your info -->
        	<div class="box box-success">
                <div class="box-header">
                    <!-- tools box -->
                    <div class="pull-right box-tools">
                        <button class="btn btn-primary btn-sm pull-right" data-widget='collapse' data-toggle="tooltip" title="Collapse" style="margin-right: 5px;"><i class="fa fa-minus"></i></button>
                    </div><!-- /. tools -->
    
                    <i class="fa fa-cloud"></i>
                    <h3 class="box-title">
                        <?php echo $_lang["yourinfo_title"]; ?>
                    </h3>
                </div>
                <div class="box-body">
                <?php include_once('welcome_user_info.phtml'); ?>
                </div>
            </div><!-- /.end box --><!-- end your info -->
            <!-- config check -->
        	<div class="box box-danger">
                <div class="box-header">
                    <!-- tools box -->
                    <div class="pull-right box-tools">
                        <button class="btn btn-primary btn-sm pull-right" data-widget='collapse' data-toggle="tooltip" title="Collapse" style="margin-right: 5px;"><i class="fa fa-minus"></i></button>
                    </div><!-- /. tools -->
    
                    <i class="fa fa-cloud"></i>
                    <h3 class="box-title">
                        <?php echo $_lang["configcheck_title"]; ?>
                    </h3>
                </div>
                <div class="box-body">
                <?php echo $config_check_results; ?>
                </div>
            </div><!-- /.end box --><!-- end config check -->
        </section><!-- /.Left col -->
        <!-- right col-->
        <section class="col-lg-6 connectedSortable">
        	<!-- recent activity -->
        	<div class="box box-warning">
                <div class="box-header">
                    <!-- tools box -->
                    <div class="pull-right box-tools">
                        <button class="btn btn-primary btn-sm pull-right" data-widget='collapse' data-toggle="tooltip" title="Collapse" style="margin-right: 5px;"><i class="fa fa-minus"></i></button>
                    </div><!-- /. tools -->
    
                    <i class="fa fa-cloud"></i>
                    <h3 class="box-title">
                        <?php echo $_lang["activity_title"]; ?>
                    </h3>
                </div>
                <div class="box-body">
                <?php include_once('welcome_recent.phtml'); ?>
                </div>
            </div><!-- /.end box --><!-- end recent activity -->
            <!-- online users -->
        	<div class="box box-primary">
                <div class="box-header">
                    <!-- tools box -->
                    <div class="pull-right box-tools">
                        <button class="btn btn-primary btn-sm pull-right" data-widget='collapse' data-toggle="tooltip" title="Collapse" style="margin-right: 5px;"><i class="fa fa-minus"></i></button>
                    </div><!-- /. tools -->
    
                    <i class="fa fa-cloud"></i>
                    <h3 class="box-title">
                        <?php echo $_lang["onlineusers_title"]; ?>
                    </h3>
                </div>
                <div class="box-body">
                <?php include_once('welcome_online_users.phtml'); ?>
                </div>
            </div><!-- /.end box --><!-- end online users -->
            
    	</section><!-- /.right col -->
    </div>
</section>