<div class="header">
        <?php echo $this->etomite->config['site_name'];?> - <?php echo $this->moduleConfig['name'];?> Administration
</div>

<div class="content">
    <?php
    /*foreach ($this->moduleConfig as $key=>$val) {
        echo "<p>" . $key . ": " . $val . "</p>";
    }*/
    ?>
    <?php include_once $this->moduleDir . '/views/admin_nav.phtml';?>
    <?php $this->listGalleries(); ?>
</div>