<div class="editItem">
    <table width="100%" cellpadding="5" cellspacing="0" border="0">
        <tr><td><strong>Title:</strong></td><td><input type="text" name="item_title" id="item_title" value="<?php echo $item['title']; ?>" /></td></tr>
        <tr><td><strong>Add to Slides:</strong></td><td><input name="item_slide" id="item_slide" type="checkbox" value="1" <?php echo $slide_checked;?> /></td></tr>
        <tr><td valign="top"><strong>Description:</strong></td><td><textarea rows="6" cols="40" name="item_description" id="item_description"><?php echo $item['description']; ?></textarea></td></tr>
        <tr><td colspan="2" align="right"><input type="button" id="editItemBtn" value="Update Item" /></td></tr>
    </table>
</div>