<!-- <link type="text/css" href="/modules/mod_gallery/css/smoothness/jquery-ui-1.8.16.custom.css" rel="stylesheet" />
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script> -->
<script type="text/javascript" src="/modules/mod_gallery/js/mod_gallery.js"></script>

<div class="header">
    <?php echo $this->moduleConfig['name'];?> - Gallery Items for <?php echo $gallery['name']; ?>
</div>

<div class="content">
<?php include_once $this->moduleDir.'/views/admin_nav.phtml';?>
<?php if($items){ ?>
<form method='post'name='orderForm' action=''>
    <table width='100%' cellpadding='3' border='1' class='gall-list'>
        <tr><td colspan='5' align='right'><input type='submit' name='submit' value='Save Order' /></td></tr>
        <tr><th>Image</th><th>Information</th><th>Add to Slides</th><th>Order</th><th>Actions</th></tr>
        <?php
        foreach ($items as $item) {
            $gItems[] = $item['id'];
			$output .= "<tr>";
			$output .= "<td align='center' width='150' valign='middle'>";
			if (file_exists($this->www.$this->thumbs."th_".$item['fn'])) {
			    $output .= "<img src='".$this->www.$this->thumbs."th_".$item['fn']."' border='0' />";
			} else {
			    $output .= "<p>File not found!</p>";
			}
			$output .= "</td>";
			$output .= "<td valign='top'><p><strong>Title:</strong>".stripslashes($item['title'])."</p><p><strong>Description:</strong><br />".stripslashes($item['description'])."</p></td>";
			
			$output .= "<td valign='middle' align='center' width='75'>";
			if($item['slide']==1){ $output .= "<span class='slide-on'>YES</span>"; }else{ $output .= "&nbsp;"; }
			$output .= "</td>";
			// order
			$output .= "<td valign='middle' align='center' width='75'><input type='text' size='5' maxchars='2' name='item_".$item['id']."_order' value='".$item['gal_order']."' /></td>";
			// actions for the item
			$output .= "<td align='center' width='75'><a href='javascript:;' onclick='editItem(".$item['id'].",".$gallery['id'].");'>EDIT</a><br /><a href='javascript:;' onclick='deleteItem(".$item['id'].",".$gallery['id'].");'>DELETE</a></td>";
			$output .= "</tr>";
            
        }
        $_SESSION['gItems'] = $gItems; // used for updating order
        echo $output;
        ?>
        
    </table>
</form>
<?php } else { ?>
<h2>Sorry no gallery items to show! Please upload some images</h2>
<?php } ?>
</div>
<div id="editDialog"></div>
<div id="deleteDialog"></div>